### ISSUE TITLE
Unable to install?

### ISSUE THREAD

**Issue by Gamedirection** [Ghostkeeper/X3GWriter#12]
After dropping the X3GWriter-master file from the zip directly into the plugin folder of Cura, Cura does not seem to recognize it is installed? Help?

**Comment by Ghostkeeper** [comment]
Perhaps an easier way nowadays is to go in the top of the screen to Toolbox -> Browse packages... and then find the X3GWriter under the plug-ins category.

Alternatively you could go to [releases](https://github.com/Ghostkeeper/X3GWriter/releases) instead and download the file there of the latest release. That should work better than dropping the source code onto Cura.
