### ISSUE TITLE
Gpx provided with X3Gwriter doesn't launch

### ISSUE THREAD

**Issue by MateuszKrawczuk** [Ghostkeeper/X3GWriter#13]
I got error "Libwinpthread-1.dll is missing" when I try manually launch gpx.exe

**Comment by Ghostkeeper** [comment]
Does the same happen when saving a file as X3G from within Cura? If not, this is not a bug.

Cura provides libwinpthread-1.dll. You should be able to launch gpx.exe from Cura's main directory, like this:

    cd "C:\Program Files\Ultimaker Cura 3.4"
    ..\..\Users\MateuszKrawczuk\AppData\Roaming\cura\3.4\plugins\X3GWriter\X3GWriter\gpx.exe

Alternatively, you could copy libwinpthread-1.dll from Cura's installation folder to wherever gpx.exe is and it should run.

**Comment by Ghostkeeper** [comment]
I consider launching gpx.exe from the correct folder a sufficient workaround. Or not using gpx.exe manually at all, of course. I don't need to support that.
