### ISSUE TITLE
Bundle GPX in releases?

### ISSUE THREAD

**Issue by d235j** [Ghostkeeper/X3GWriter#2]
Would it make sense to bundle GPX in releases to make this easier to use? Would require some logic in the Python script to detect OS and call the appropriate executable.

**Comment by d235j** [comment]
Hmm, looks like this is already done with the releases included with Cura 3 beta. Closing :)

**Comment by Ghostkeeper** [comment]
The logic is in there: https://github.com/Ghostkeeper/X3GWriter/blob/d5dd7cdcd1988cd289f91882342b783f26be166d/X3GWriter.py#L57

The CMake script is currently aimed at releasing for one platform, so if you build from source you're going to build for one platform. I haven't taken the time/effort to cross compile all three and automatically create a release that works on all three, so you'll have to manually put the binaries in.
