### ISSUE TITLE
Variant behavior based on presence of `file_formats` in profile

### ISSUE THREAD

**Issue by stuartpb** [Ghostkeeper/X3GWriter#22]
See stuartpb/repligreater#2 and Ultimaker/Cura#5009 - there's an upstream bug that lives in either this project or that one.

I'd investigate further, but the condescending crap I got from Ultimaker [the last time I tried to fix one of their problems](https://github.com/Ultimaker/Cura/issues/1296#issuecomment-354716603) (especially the part where issues kept getting moved to a proprietary company-internal tracker, where the Project Manager could then silently smother them in their sleep), at the beginning of the year, caused me to rethink my entire code-to-plastic pipeline. These days, I happily spend my time on an [i3 MK3](https://shop.prusa3d.com/en/3d-printers/180-original-prusa-i3-mk3-kit.html), slicing prints using [Slic3r Prusa Edition](https://github.com/prusa3d/Slic3r) (which, unlike Cura, I've found to be well-supported with *any* manufacturer's printer).

**Comment by Ghostkeeper** [comment]
Thanks for the heads-up. I've done some investigation and posted my findings in stuartpb/repligreater#2, since that issue has the most information. I'll close this as a duplicate.
