### ISSUE TITLE
Installation of plug-in

### ISSUE THREAD

**Issue by delidel97** [Ghostkeeper/X3GWriter#36]
Can someone please advise how to actually install these files so they work on Cura; I've downloaded them w=however have no idea how to install. Please help.

I am trying to combat this error on Cura for reference

Thanks! 
![115929810_672734386790143_3578848158845197808_n](https://user-images.githubusercontent.com/69047085/89047017-21dbe800-d391-11ea-8cc2-cdce6df07cb7.jpg)

**Comment by Ghostkeeper** [comment]
The easiest way is to go into the Marketplace:
![image](https://user-images.githubusercontent.com/2448634/89050020-6b591280-d352-11ea-81c5-ba29a07b6518.png)

Then find the X3GWriter down in the list. It's alphabetical so it'll be near the bottom:
![image](https://user-images.githubusercontent.com/2448634/89050257-c854c880-d352-11ea-8101-1e5eaf0a40e8.png)

In that page you'll click on the big blue "Install" button:
![image](https://user-images.githubusercontent.com/2448634/89050314-df93b600-d352-11ea-9951-6e814add6bb8.png)

Then restart Cura, and it should be installed.

**Comment by Ghostkeeper** [comment]
Note that this plug-in doesn't allow you to *open* X3G files. It just allows you to *save* them. I don't know when you were getting that error?

**Comment by delidel97** [comment]
Thank you so much!!! I am so grateful for your help

**Comment by delidel97** [comment]
I was receiving this error when trying to save my sliced files to my USB
before I installed the plug in. Now that I have installed the plug in I was
able to save the sliced file to my drive so I’m guessing this means it has
worked and I can print this file
