### ISSUE TITLE
X3GWriter as post-processing script for Slic3r/Simplify3D?

### ISSUE THREAD

**Issue by Meganium97** [Ghostkeeper/X3GWriter#46]
Would it be possible to make a version of X3GWriter as a post processing script for Slic3r/Simplify3D? It could possibly just require a simple change to support the different 3d printers.

**Comment by Ghostkeeper** [comment]
What you're looking for is a wrapper around the GPX application itself: https://github.com/markwal/GPX
This is an executable application that does the actual conversion. This plug-in is basically just an adaptation that makes it easy to use that GPX application from within Cura. It integrates GPX with Cura.

Developing a similar plug-in for Slic3r or Simplify3D is out of scope, sorry. It would best be done in a completely different project anyway. Cura is my expertise, not Slic3r or Simplify3D.
